### PR TITLE
Rework the RDF output a little

### PR DESCRIPTION
**Pull request by pypingou**
I replaced the /get-attributes/<term>/rdf by a /rdf/<term> which will make things much easier for the future. I did not preserve backward compatibility as this is still pretty new work and I assume we are not so many to use it yet.

I also re-work a little the RDF output hoping it generates the URL correctly this time.

Thanks

### CODE REVIEW

**Comment by lmatteis** [comment]
Hey pypingou. I'm out for work conference up until the end of the month. Once I get back I'll test these changes out and merge them. Thanks so much.

**Comment by pypingou** [comment]
Have fun at the conference then :)

**Comment by pypingou** [comment]
Rebased against master

**Comment by pypingou** [comment]
Rebased against master

**Comment by pypingou** [comment]
Any news for this one ?

**Comment by lmatteis** [comment]
Hey @pypingou Yes I'll upload the changes by tomorrow

**Comment by pypingou** [comment]
Did something go wrong ?

**Comment by lmatteis** [comment]
damn, sorry i forgot about merging this. Running tests now and will deploy to the actual site asap
thanks!

**Comment by lmatteis** [comment]
@pypingou sorry but some tests aren't passing as I updated to version 1.7.0 of appengine's framework. As soon as I figured them out I'll upload these changes to the site.

**Comment by pypingou** [comment]
On Thu, 2012-07-26 at 02:11 -0700, Luca Matteis wrote:

> @pypingou sorry but some tests aren't passing as I updated to version 1.7.0 of appengine's framework. As soon as I figured them out I'll upload these changes to the site.
> 
> Thanks for the info, keep me in the loop!

Pierre

**Comment by lmatteis** [comment]
Ok it's uploaded finally! :) sorry for delay

**Pull request merged**
