### PR TITLE
Add a "jsonrdf" version of the attribute output

### PR DESCRIPTION
**Pull request by pypingou**
In this version the json is annotated with elements from other ontologies adding semantic to the output

### CODE REVIEW

**Comment by lmatteis** [comment]
Can you add these two calls above the /get-attributes call? The order is important based on the regex you're doing.

**Comment by pypingou** [comment]
Reordering done (and I remove the call to /rdf which was actually a mistake)

**Comment by lmatteis** [comment]
There were a bit of syntax errors that i fixed. Pull the version from my master whenever you can. Also it's uploaded to the live site!

**Comment by pypingou** [comment]
Thanks for all this :)

**Pull request merged**
