### PR TITLE
Fix the XML structure itself

### PR DESCRIPTION
**Pull request by pypingou**
- Add missing /rdf:RDF tag
- Add missing /oboInOwl:Definition
- Remove un-necessary oboInOwl:Definition
- Add missing reference to the OWL ontology

XML document should be valid now

### CODE REVIEW

**Comment by pypingou** [comment]
There are still some issues with the links within the XML document which we have to sort out

(see in http://www.cropontology.org/get-attributes/CO_334:0000019/rdf the 'rdfs:subClassOf' element)

**Comment by lmatteis** [comment]
Okay. I'll wait until all the XML definitions are there before merging this one.

**Comment by pypingou** [comment]
Well at least with this one we produce valid XML (which isn't the case atm)

**Comment by lmatteis** [comment]
Oh ok. i'll merge then :)

**Pull request merged**
